<?php
namespace App\Models;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class UserPermission extends Model
{
    use HasFactory;

    protected $fillable = [
    	'user_id',
        'module',
        'status'
    ];

    public static $access_module = [
        "1" => array(
            "create_order" => "Create Order",
            "view_order" => "View Order",
            "edit_order" => "Edit Order",
            "order_status" => "Manage Order Status",
            "assign_driver" => "Assign Driver",
            "rewash_request" => "Rewash Request",
            "cancel_request" => "Cancel Request",
            "order_status_screen" => "Order Status Screen",
            "garment_status_screen" => "Garment Status Screen",
            "packing_sticker" => "Packing Sticker",
            "expense_list" => "Expense List",
            "expense_category" => "Expense Category",
            "customer" => "Customers",
            "add_customer" => "Add Customer",
            "assign_membership" => "Assign Membership to Customer",
            "manage_category" => "Manage Category",
            "manage_service_type" => "Manage Service Type",
            "manage_garments" => "Manage Garments",
            "manage_addons" => "Manage Addons",
            "manage_rate_chart" => "Manage Rate Chart",
            "daily_report" => "Daily Report",
            "order_report" => "Order Report",
            "sales_report" => "Sales Report",
            "expense_report" => "Expense Report",
            "tax_report" => "Tax Report",
            "garment_report" => "Garment Report",
            "customer_order_report" => "Customer Order Report",
            "customer_history_report" => "Customer History Report",
            "outlet_report" => "Outlet Report",
            "workstation_report" => "Workstation Report",
            "workstation_summary_report" => "Workstation Summary Report",
            "outstanding_report" => "Outstanding Report",
            "stock_report" => "Stock Report",
            "rewash_report" => "Rewash Report",
            "service_report" => "Service Report",
            "financial_year" => "Financial Year",
            "mail_settings" => "Mail Settings",
            "master_settings" => "Master Settings",
            "file_tools" => "File Tools",
            "sms_settings" => "SMS Settings",
            "membership" => "Membership",
            "manage_user" => "Manage User",
            "manage_outlet" => "Manage Outlet",
            "manage_workstation" => "Manage Workstation",
            "manage_brand" => "Manage Brand",
            "manage_voucher" => "Manage Voucher",
            "manage_delivery" => "Manage Delivery Master",
            "manage_promotion" => "Manage Promotion",
            "user_permission" => "User Permission",

        ),
        "2" => array(
           "create_order" => "Create Order",
           "view_order" => "View Order",
            "edit_order" => "Edit Order",
            "order_status" => "Manage Order Status",
            "assign_driver" => "Assign Driver",
            "order_status_screen" => "Order Status Screen",
            "garment_status_screen" => "Garment Status Screen",
            "customer" => "Customers",
            "assign_membership" => "Assign Membership to Customer",
            "expense_list" => "Expense List",
            "expense_category" => "Expense Category",
            "daily_report" => "Daily Report",
            "order_report" => "Order Report",
            "sales_report" => "Sales Report",
            "expense_report" => "Expense Report",
            "tax_report" => "Tax Report",
            "garment_report" => "Garment Report",
            "customer_order_report" => "Customer Order Report",
            "customer_history_report" => "Customer History Report",
            "outlet_report" => "Outlet Report",
            "workstation_report" => "Workstation Report",
            "workstation_summary_report" => "Workstation Summary Report",
            "outstanding_report" => "Outstanding Report",
            "stock_report" => "Stock Report",
            "rewash_report" => "Rewash Report",
            "service_report" => "Service Report",
            "manage_voucher" => "Manage Voucher",
            "user_permission" => "User Permission",
        ),
        "3" => array(
            "rewash_request" => "Rewash Request",
            "cancel_request" => "Cancel Request",
            "garment_status_screen" => "Garment Status Screen",
            "packing_sticker" => "Packing Sticker",
            "customer" => "Customers",
            "expense_list" => "Expense List",
            "expense_category" => "Expense Category",
            "daily_report" => "Daily Report",
            "order_report" => "Order Report",
            "sales_report" => "Sales Report",
            "expense_report" => "Expense Report",
            "tax_report" => "Tax Report",
            "garment_report" => "Garment Report",
            "customer_order_report" => "Customer Order Report",
            "customer_history_report" => "Customer History Report",
            "outlet_report" => "Outlet Report",
            "workstation_report" => "Workstation Report",
            "workstation_summary_report" => "Workstation Summary Report",
            "outstanding_report" => "Outstanding Report",
            "stock_report" => "Stock Report",
            "rewash_report" => "Rewash Report",
            "service_report" => "Service Report",
            "manage_voucher" => "Manage Voucher",
            "manage_promotion" => "Manage Promotion",
            "user_permission" => "User Permission",
        ),
        "4" => array(),
    ];
}